### PR TITLE
Fix on refuel tooltip price display

### PR DESCRIPTION
**Pull request by JPS09**
**Before**
image
**After**
image

### CODE REVIEW

**Comment by sbriclot** [comment]
Normally this problem of format for prices was fixed with Pull Request #60, some migrations were added to shrink the existing prices then change the precision of this column.
These migrations were not applied on production ?

**Comment by JPS09** [comment]
I thought about this too but for some reason it's displaying like this... I will try to check at home what are the values of the prices directly from the prod. I will try to keep you updated 😉

**Comment by sbriclot** [comment]
On Prod we have long floats with large precision.
image

image

My current dev env
image

**Comment by JPS09** [comment]
Ok I know why, it's because I applied this fix through a migration which is only run one time so if you seeded after that, the new elements are not influenced by that fix. I had issues truncating the information in the db when I tried modifiying the precision of those columns because of the existing values, maybe you have a solution for that?

**Comment by JPS09** [comment]
Just for information, how did you linked DBeaver to the prod database ? It would be very helpful! 😉

**Comment by sbriclot** [comment]
In the console, execute the following command to get the database URL :
heroku config:get DATABASE_URL

Then create a new connection in DBeaver using this schema :
image

**Comment by JPS09** [comment]
Thank you ! I will try to fiddle with this from DB beaver to apply the correct precision on the current data if that's ok for you ? 😊

**Comment by sbriclot** [comment]
That's ok for me, I think I've updated my local version like that.
Feel free to mail or call me if you have some trouble with this update.

**Comment by JPS09** [comment]
The issue was that I did not run the migration in the prod environment 🤕 I forgot that heroku does not run them when it recreates the prod after a push on master... Do you still want to have a safe guard in the JS thanks to this PR or do I close it?

**Comment by sbriclot** [comment]
You can merge you change, a second level of control is never too much until it doesn't impact the performance, and there's no risk of slowdown here.

**Pull request merged**
